### ISSUE TITLE
Bug: Error while saving image in profile

### ISSUE THREAD

**Issue by majorbruteforce** [Brijendra-Singh2003/BootCamp_2.0#1]
Issue Description: 
While uploading/updating the profile picture in the profile page the 'save' button changes to 'saving' and just freezes. It doesn't indicate the status of the request (success or failure). The profile picture is not updated as well. 

Expected Behavior:
- After clicking the button, the request status must be indicated (success or failure).
- The photo must be updated.

Current Behavior:
- The status indicates only that the upload is pending and is not resolved.
- The image is not uploaded/updated.

Steps to reproduce: 
1. Go to profile page
2. Click on 'Drag and Drop here' and upload an image
3. Click on 'Save'

![Screenshot (32)](https://github.com/Brijendra-Singh2003/BootCamp_2.0/assets/131452403/eacac0b2-5b6a-4351-86ce-d5b4168f225c)

**Comment by Brijendra-Singh2003** [comment]
Fixed,
You need to refresh the page after successful upload in order to view
changes. That will be fixed soon 🙂
